server:
  port: 8091

#mysql数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.62.130:3306/mk_test_database?useUnicode=true&characterEncoding=utf-8&&userSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxCreateTaskCount: 10
    initialize: true
#    应用的别名（非项目访问路径），可以不加
  application:
    name: order-service


#  eureka服务端信息配置
eureka:
  client:
    #    将自己注册到eureka上
    register-with-eureka: false
    #    是否从服务端抓取注册信息
    fetch-registry: true
    service-url:
      # 入驻地址
      defaultZone: http://eureka8083.com:8083/eureka/,http://eureka8084.com:80834/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    #feign以什么级别监控某个接口
    com.mk.service.PaymentService: debug