server:
  port: 8091


spring:
#    应用的别名（非项目访问路径），可以不加
  application:
    name: order-service
  zipkin:
    base-url: http://192.168.62.130:9411
    sleuth:
      sampler:
        #采样率0到1之间，1为全部采集
        probability: 1

#  eureka服务端信息配置
eureka:
  client:
    #    将自己注册到eureka上
    register-with-eureka: true
    #    是否从服务端抓取注册信息
    fetch-registry: true
    service-url:
      # 入驻地址
    #  defaultZone: http://eureka8083.com:8083/eureka/,http://eureka8084.com:80834/eureka/
      defaultZone: http://eureka8083.com:8083/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    #feign以什么级别监控某个接口
    com.mk.service.PaymentService: debug