server:
  port: 8081
#mysql数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.62.130:3306/mk_test_database?useUnicode=true&characterEncoding=utf-8&&userSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxCreateTaskCount: 10
    initialize: true

  application:
    #    应用的别名;向eureka注册时时不能带下划线，会导致服务无法找到
    name: payment-service
  zipkin:
    base-url: http://192.168.62.130:9411
    sleuth:
      sampler:
        #采样率0到1之间，1为全部采集
        probability: 1
#mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/mk/mapper/*Mapper.xml
#  eureka服务端信息配置
eureka:
  client:
#    将自己注册到eureka上
    register-with-eureka: true
#    是否从服务端抓取注册信息
    fetch-registry: true
    service-url:
# 入驻地址
      defaultZone: http://eureka8083.com:8083/eureka/
  instance:
    instance-id: payment-service-8081 #实例名称
    prefer-ip-address: true  #
    lease-renewal-interval-in-seconds: 1 #心跳频率，单位为秒 默认为30
    lease-expiration-duration-in-seconds: 90    #心跳超时则剔除服务