server:
  port: 8086
#mysql数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.62.130:3306/mk_test_database?useUnicode=true&characterEncoding=utf-8&&userSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxCreateTaskCount: 10
    initialize: true
  application:
    #    应用的别名
    name: payment-service
  cloud:
    zookeeper:
      connect-string: 192.168.62.130:2181
#mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/mk/mapper/*Mapper.xml
